import Web3 from 'web3';
import type { NextPage } from 'next'
import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../styles/Home.module.css'
import configuration from '../../build/contracts/Tickets.json'
import {useEffect, useState} from 'react';

const CONTRACT_ADDRESS:any = configuration.networks[5777].address;
const CONTRACT_ABI:any = configuration.abi;

const web3 = new Web3(Web3.givenProvider || 'http://127.0.0.1:7545');

const contract = new web3.eth.Contract(CONTRACT_ABI, CONTRACT_ADDRESS);
let account:string;

const Home: NextPage = () => {

  const [accountEl, setAccountEl] = useState('')
  const [ticketsEl, setTicketsEl] = useState([])


  const main = async () => {
    const accounts = await web3.eth.requestAccounts();
    account = accounts[0];
    setAccountEl(account);
  }

  const getTickets = async () => {
    let ticketArray:any = []
    console.log("GOT HERE");

    for ( let i =0; i < 10; i++ ) {
      const item =  await contract.methods.tickets(i).call();
      console.log(item);

      if(!item.isSold){
        ticketArray.push(item);
      }
    }

    setTicketsEl(ticketArray);
  }

  

  useEffect(() => {
    main();
    getTickets();
  }, [])

  async function buyTicket(index:number, price:number){

    await contract.methods.buyTicket(index).send(
      {from:account, value:price}
      )

    getTickets();
  }


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="navbar navbar-light bg-light">
      <div className="container">
        <a className="navbar-brand">Navbar</a>
        <div id="account" className="d-flex">
        {accountEl}
        </div>
      </div>
    </nav>

      <main  className={styles.main}>
      
        <h1 className={styles.title}>
          Welcome
        </h1>

        <div id={styles.tickets} className="my-3">
          {ticketsEl.map((ticket:any, index) =>{

            return(

              <div key={index}  className={`${styles.ticket} card mx-2`}>
                <div className="card-body text-center">
                  <h5 className="card-title">{ticket.price / 1e18} ETH</h5>
                  <button className="btn btn-primary btn-sm " onClick={()=> buyTicket(index, ticket.price)}>Buy Ticket</button>
                </div>
            </div>

            )
            
          })}

        </div>

 

      </main>

      <footer className={styles.footer}>
        <a
          href="#"
        >
          Powered by{' '}
          <span>
            Bochie
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
